# Generated by Django 4.1.7 on 2023-04-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=250, null=True)),
                ('skills', models.CharField(max_length=250, null=True)),
                ('edit_image', models.FileField(blank=True, null=True, upload_to='employee_img/')),
                ('about', models.CharField(blank=True, max_length=250, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_account.employee')),
            ],
        ),
    ]
