# Generated by Django 4.1.7 on 2023-04-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_account', '0002_profile_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_details',
            old_name='edit_image',
            new_name='profile_img',
        ),
    ]
